services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./db_mysql:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./db_redis:/data